version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.7.1
caches: 
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}
commands:
  run_linters:
    description: command to start linters
    steps:
      - run: 
          name: rubocop
          command: bundle exec rubocop
           
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
jobs:
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_linters

workflows:
  version: 2
  build:
    jobs:
      - lintering

